// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtDP9uRdqzBNv1N0w80CZYZWw3lvLwsjM',
    appId: '1:1082504661197:web:0f0baf18aef2dfb60ec184',
    messagingSenderId: '1082504661197',
    projectId: 'english-volcabulary-card',
    authDomain: 'english-volcabulary-card.firebaseapp.com',
    databaseURL: 'https://english-volcabulary-card-default-rtdb.firebaseio.com',
    storageBucket: 'english-volcabulary-card.firebasestorage.app',
    measurementId: 'G-5M6P5K3ZP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn7Gq9jLcrDxPXr026hR3U0qX29czqm7g',
    appId: '1:1082504661197:android:efed9cf1e89beaa20ec184',
    messagingSenderId: '1082504661197',
    projectId: 'english-volcabulary-card',
    databaseURL: 'https://english-volcabulary-card-default-rtdb.firebaseio.com',
    storageBucket: 'english-volcabulary-card.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqijJW5_gZzEQVtwRWC42RX9Kru2gDW5k',
    appId: '1:1082504661197:ios:47516a57b6de88cd0ec184',
    messagingSenderId: '1082504661197',
    projectId: 'english-volcabulary-card',
    databaseURL: 'https://english-volcabulary-card-default-rtdb.firebaseio.com',
    storageBucket: 'english-volcabulary-card.firebasestorage.app',
    iosClientId:
        '1082504661197-8lgn48ajr73qkb0ebjo9dahs4ljssrog.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVocabularyCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqijJW5_gZzEQVtwRWC42RX9Kru2gDW5k',
    appId: '1:1082504661197:ios:47516a57b6de88cd0ec184',
    messagingSenderId: '1082504661197',
    projectId: 'english-volcabulary-card',
    databaseURL: 'https://english-volcabulary-card-default-rtdb.firebaseio.com',
    storageBucket: 'english-volcabulary-card.firebasestorage.app',
    iosClientId:
        '1082504661197-8lgn48ajr73qkb0ebjo9dahs4ljssrog.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVocabularyCard',
  );
}
