"""Check vocabulary structure and synchronize explicitly reviewed entries.

The checker cannot prove semantic accuracy or CEFR level. Reviews are written
by an editor in docs/vocabulary_reviews.json, with dictionary references.
"""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
REVIEWS_PATH = ROOT / 'docs/vocabulary_reviews.json'
GENERATED_PATH = ROOT / 'lib/features/vocabulary/data/models/vocabulary_content_review.entries.dart'
REQUIRED = ('word', 'partOfSpeech', 'definition', 'example', 'chineseTranslation')
PARTS = {
    'noun', 'verb', 'adjective', 'adverb', 'preposition', 'determiner',
    'abbreviation', 'pronoun', 'numeral', 'modal verb',
    'verb, noun', 'noun, verb', 'adjective, noun',
}


def dart_string(value):
    return json.dumps(value, ensure_ascii=False).replace('$', r'\$')


def generated_reviews(reviews):
    lines = [
        '// GENERATED by scripts/audit_vocabulary.py --apply-reviews.',
        '// Edit docs/vocabulary_reviews.json instead.',
        "part of 'vocabulary_content_review.dart';", '',
        'const _contentReviews = <Map<String, dynamic>>[',
    ]
    for review in reviews:
        lines.append('  {')
        for field in ('word', 'partOfSpeech', 'originalDefinition', 'originalExample'):
            lines.append(f'    {dart_string(field)}: {dart_string(review[field])},')
        lines.append('    "replacement": <String, String>{')
        for field, value in review['replacement'].items():
            lines.append(f'      {dart_string(field)}: {dart_string(value)},')
        lines.extend(['    },', '  },'])
    lines.extend(['];', ''])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--apply-reviews', action='store_true',
                        help='Update known bundled entries and generate runtime reviews.')
    args = parser.parse_args()
    reviews = json.loads(REVIEWS_PATH.read_text())
    files = {path: json.loads(path.read_text())
             for path in sorted((ROOT / 'assets/data').glob('[A-Z].json'))}
    errors = []
    ids = set()
    senses = set()
    reviewed = set()

    for review in reviews:
        replacement = review['replacement']
        if not all(isinstance(replacement.get(field), str) and replacement[field].strip()
                   for field in ('definition', 'example', 'chineseTranslation', 'usageNote', 'sourceUrl')):
            errors.append(f"Invalid review: {review['word']}")
        if not replacement.get('sourceUrl', '').startswith('https://'):
            errors.append(f"Review needs a source: {review['word']}")

    for path, entries in files.items():
        for entry in entries:
            label = f"{path.name}: {entry.get('word', '?')}"
            matching = [review for review in reviews
                        if entry.get('word') == review['word']
                        and entry.get('partOfSpeech') == review['partOfSpeech']]
            for review in matching:
                replacement = review['replacement']
                known = (entry.get('definition') in (review['originalDefinition'], replacement['definition'])
                         and entry.get('example') in (review['originalExample'], replacement['example']))
                if not known:
                    errors.append(f'{label}: review no longer matches; inspect before editing')
                    continue
                reviewed.add((review['word'], review['partOfSpeech']))
                if args.apply_reviews:
                    entry.update(replacement)
                elif any(entry.get(field) != value for field, value in replacement.items()):
                    errors.append(f'{label}: reviewed correction not synchronized')

            entry_id = entry.get('id')
            if (not isinstance(entry_id, (int, str)) or isinstance(entry_id, bool)
                    or not str(entry_id).strip()):
                errors.append(f'{label}: invalid id')
            elif str(entry_id) in ids:
                errors.append(f'{label}: duplicate id {entry_id}')
            ids.add(str(entry_id))
            for field in REQUIRED:
                value = entry.get(field)
                if not isinstance(value, str) or not value.strip():
                    errors.append(f'{label}: missing {field}')
                elif value != value.strip():
                    errors.append(f'{label}: whitespace in {field}')
            if entry.get('partOfSpeech') not in PARTS:
                errors.append(f'{label}: unknown part of speech')
            sense = (entry.get('word', '').casefold(), entry.get('partOfSpeech'))
            if sense in senses:
                errors.append(f'{label}: duplicate word + part of speech')
            senses.add(sense)
            if not entry.get('word', '').upper().startswith(path.stem):
                errors.append(f'{label}: wrong letter file')

    for review in reviews:
        if (review['word'], review['partOfSpeech']) not in reviewed:
            errors.append(f"Review has no matching entry: {review['word']}")

    generated = generated_reviews(reviews)
    if not args.apply_reviews and (not GENERATED_PATH.exists()
                                  or GENERATED_PATH.read_text() != generated):
        errors.append('Runtime reviews differ from the review manifest; run --apply-reviews')
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    if args.apply_reviews:
        for path, entries in files.items():
            text = json.dumps(entries, ensure_ascii=False, indent=2) + '\n'
            # Preserve untouched files and their existing formatting.
            if json.loads(path.read_text()) != entries:
                path.write_text(text)
        GENERATED_PATH.write_text(generated)
    count = sum(len(entries) for entries in files.values())
    print(f'PASS: {count} entries in {len(files)} files; {len(reviewed)} reviewed senses synchronized.')
    print('Structural checks passed. Other senses and CEFR levels still need editorial review.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
